import type { Metadata } from "next"
import "./globals.css"
import { Navbar, NavbarOption } from "@components/ui/navbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar>
          <NavbarOption displayName="Home" uri="/" />
          <NavbarOption displayName="Lotus Water Calculator" uri="/water" />
        </Navbar>
        <div className="p-4">
          {children}
        </div>
        <div className="dot-mask -z-30" />
        <footer className="mt-4">
          <hr className="border-4 border-black border-dashed" />
          <p className="text-center m-4 text-gray-400">
            Made with love and a lot of coffee.
            <sup><a href="https://github.com/Shikachuu/open-brew-tools">Find the source code here!</a></sup>
          </p>
        </footer>

      </body>
    </html>
  )
}
